In [1]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd

In [14]:
df = pd.read_csv('bank_sample.csv')
df.head()

age  duration  campaign  pdays  previous  emp.var.rate  cons.price.idx  \
0   39       156         5    999         0           1.4          94.465   
1   25       103         1    999         0           1.4          93.918   
2   50       121         2    999         0           1.1          93.994   
3   45       187         1    999         0           1.4          93.444   
4   46       124         4    999         0          -1.8          93.075   

   cons.conf.idx  euribor3m  nr.employed  ...  job  marital  education  \
0          -41.8      4.865       5228.1  ...    4        1          1   
1          -42.7      4.963       5228.1  ...    0        2          3   
2          -36.4      4.859       5191.0  ...    9        1          5   
3          -36.1      4.965       5228.1  ...    1        1          0   
4          -47.1      1.405       5099.1  ...    7        1          3   

   default  housing  loan  contact  month  day_of_week  poutcome  
0        1        0     0        1      4            1         1  
1        0        2     0        0      3            2         1  
2        0        0     0        1      6            0         1  
3        1        2     2        0      1            1         1  
4        0        0     0        0      0            1         1  

[5 rows x 22 columns]

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3295 entries, 0 to 3294
Data columns (total 22 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             3295 non-null   int64  
 1   duration        3295 non-null   int64  
 2   campaign        3295 non-null   int64  
 3   pdays           3295 non-null   int64  
 4   previous        3295 non-null   int64  
 5   emp.var.rate    3295 non-null   float64
 6   cons.price.idx  3295 non-null   float64
 7   cons.conf.idx   3295 non-null   float64
 8   euribor3m       3295 non-null   float64
 9   nr.employed     3295 non-null   float64
 10  purchased       3295 non-null   int64  
 11  id              3295 non-null   int64  
 12  job             3295 non-null   int64  
 13  marital         3295 non-null   int64  
 14  education       3295 non-null   int64  
 15  default         3295 non-null   int64  
 16  housing         3295 non-null   int64  
 17  loan            3295 non-null   i

In [6]:
df.purchased.value_counts()

0    2940
1     355
Name: purchased, dtype: int64

Split

In [8]:
import sklearn
from sklearn.model_selection import train_test_split

In [16]:
x = df.drop('purchased',axis=1)
x.head()

age  duration  campaign  pdays  previous  emp.var.rate  cons.price.idx  \
0   39       156         5    999         0           1.4          94.465   
1   25       103         1    999         0           1.4          93.918   
2   50       121         2    999         0           1.1          93.994   
3   45       187         1    999         0           1.4          93.444   
4   46       124         4    999         0          -1.8          93.075   

   cons.conf.idx  euribor3m  nr.employed  ...  job  marital  education  \
0          -41.8      4.865       5228.1  ...    4        1          1   
1          -42.7      4.963       5228.1  ...    0        2          3   
2          -36.4      4.859       5191.0  ...    9        1          5   
3          -36.1      4.965       5228.1  ...    1        1          0   
4          -47.1      1.405       5099.1  ...    7        1          3   

   default  housing  loan  contact  month  day_of_week  poutcome  
0        1        0     0        1      4            1         1  
1        0        2     0        0      3            2         1  
2        0        0     0        1      6            0         1  
3        1        2     2        0      1            1         1  
4        0        0     0        0      0            1         1  

[5 rows x 21 columns]

In [17]:
y = df.pop('purchased')
y.head()

0    0
1    0
2    0
3    0
4    0
Name: purchased, dtype: int64

In [31]:
X_train,X_test, y_train, y_test = train_test_split(x,y, train_size = 0.7, random_state = 42)
X_train.shape, X_test.shape

((2306, 21), (989, 21))

In [20]:
df.shape

(3295, 21)

In [21]:
import os
os.environ["PATH"] += os.pathsep + 'C:\Program Files (x86)\Graphviz2.38\bin'

Random forest Model

In [22]:
from sklearn.ensemble import RandomForestClassifier

In [28]:
rf = RandomForestClassifier(bootstrap=True,
criterion='gini',
max_depth=3,
n_estimators=10,
oob_score=True,
random_state=42)

In [32]:
rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=3, n_estimators=10, oob_score=True,
                       random_state=42)

In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [35]:
def evaluate_model(classifier):
    print("Train Accuracy :", accuracy_score(y_train, classifier.predict(X_train)))
    print("Train Confusion Matrix:")
    print(confusion_matrix(y_train, classifier.predict(X_train)))
    print("-"*50)
    print("Test Accuracy :", accuracy_score(y_test, classifier.predict(X_test)))
    print("Test Confusion Matrix:")
    print(confusion_matrix(y_test, classifier.predict(X_test)))

In [43]:
#Train accuracy
y_pred = rf.predict(X_train)
accuracy_score(y_pred,y_train)


0.9032957502168256

In [47]:
#Test_accuracy
y_test_pred = rf.predict(X_test)
accuracy_score(y_test_pred, y_test)

0.9110212335692619

In [48]:
rf.oob_score_

0.8946227233304423

In [36]:
evaluate_model(rf)

Train Accuracy : 0.9032957502168256
Train Confusion Matrix:
[[2048    3]
 [ 220   35]]
--------------------------------------------------
Test Accuracy : 0.9110212335692619
Test Confusion Matrix:
[[884   5]
 [ 83  17]]


In [58]:
from sklearn.metrics import f1_score
from sklearn.metrics import recall_score
f1_score(y_test, y_test_pred)

0.27868852459016397

In [61]:
print('Accuracy: %.3f' % accuracy_score(y_test, y_test_pred))
print('Recall: %.3f' % recall_score(y_test, y_test_pred))
print('F1 Score: %.3f' % f1_score(y_test, y_test_pred))

Accuracy: 0.911
Recall: 0.170
F1 Score: 0.279


In [52]:
f1_score(y_train, y_pred)

0.23890784982935154

Grid Search

In [62]:
from sklearn.model_selection import GridSearchCV

In [63]:
# Create the parameter grid based on the results of random search 
params = {
    'max_depth': [1, 2, 5, 10, 20],
    'min_samples_leaf': [5, 10, 20, 50, 100],
    'max_features': [2,3,4],
    'n_estimators': [10, 30, 50, 100, 200]
}

In [64]:
classifier_rf = RandomForestClassifier(random_state=42, n_jobs=-1)

In [65]:
grid_search = GridSearchCV(estimator=classifier_rf,
                           param_grid=params,
                           cv = 4,
                           n_jobs=-1, verbose=1, scoring="accuracy")

In [66]:
grid_search.fit(x,y)

Fitting 4 folds for each of 375 candidates, totalling 1500 fits


GridSearchCV(cv=4, estimator=RandomForestClassifier(n_jobs=-1, random_state=42),
             n_jobs=-1,
             param_grid={'max_depth': [1, 2, 5, 10, 20],
                         'max_features': [2, 3, 4],
                         'min_samples_leaf': [5, 10, 20, 50, 100],
                         'n_estimators': [10, 30, 50, 100, 200]},
             scoring='accuracy', verbose=1)

In [67]:
rf_best = grid_search.best_estimator_
rf_best

RandomForestClassifier(max_depth=20, max_features=4, min_samples_leaf=5,
                       n_jobs=-1, random_state=42)

In [81]:
rf_best[0]

DecisionTreeClassifier(max_depth=20, max_features=4, min_samples_leaf=5,
                       random_state=1608637542)

In [68]:
rf_best.fit(X_train, y_train)

RandomForestClassifier(max_depth=20, max_features=4, min_samples_leaf=5,
                       n_jobs=-1, random_state=42)

In [69]:
evaluate_model(rf_best)

Train Accuracy : 0.955767562879445
Train Confusion Matrix:
[[2038   13]
 [  89  166]]
--------------------------------------------------
Test Accuracy : 0.9261880687563195
Test Confusion Matrix:
[[864  25]
 [ 48  52]]


In [70]:
### Variable importance in RandomForest and Decision trees

In [76]:
classifier_rf = RandomForestClassifier(random_state=42, n_jobs=-1, max_depth=20, n_estimators=100, oob_score=True)

In [77]:
classifier_rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=20, n_jobs=-1, oob_score=True, random_state=42)

In [78]:
classifier_rf.feature_importances_

array([0.07261608, 0.27232282, 0.03196918, 0.03196292, 0.0211948 ,
       0.02704754, 0.03778142, 0.03846613, 0.10908336, 0.06088098,
       0.08256462, 0.03999684, 0.01891777, 0.0362033 , 0.0069129 ,
       0.01458894, 0.009037  , 0.01018524, 0.02196165, 0.03469784,
       0.02160865])

In [79]:
imp_df = pd.DataFrame({
    "Varname": X_train.columns,
    "Imp": classifier_rf.feature_importances_
})

In [80]:
imp_df.sort_values(by="Imp", ascending=False)

Varname       Imp
1         duration  0.272323
8        euribor3m  0.109083
10              id  0.082565
0              age  0.072616
9      nr.employed  0.060881
11             job  0.039997
7    cons.conf.idx  0.038466
6   cons.price.idx  0.037781
13       education  0.036203
19     day_of_week  0.034698
2         campaign  0.031969
3            pdays  0.031963
5     emp.var.rate  0.027048
18           month  0.021962
20        poutcome  0.021609
4         previous  0.021195
12         marital  0.018918
15         housing  0.014589
17         contact  0.010185
16            loan  0.009037
14         default  0.006913

Duration is the most important feature 